[package]
name = "libc"
edition = "2015"
version = "0.2.151"

cargo-args = ["-Zbuild-std=core"]

[features]
default = ["std"]
std = []
align = []
rustc-dep-of-std = []
extra_traits = []
const-extern-fn = []
